services:
  - type: web
    name: hr-app-laravel
    env: docker
    dockerfilePath: ./Dockerfile
    # Render will provide the PORT environment variable automatically
    envVars:
      - key: PORT
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: hr-app-laravel
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
    buildCommand: npm ci && npm run build || echo "Frontend build skipped"
    # Run migrations but use the CMD from Dockerfile to start the server
    startCommand: php artisan migrate --force || echo "Migration skipped"
    healthCheckPath: /
    autoDeploy: true
